
# Update & deployment:
# docker build -t gcr.io/fd-slack-crypto-bot/fd-slack-crypto-bot:v1 .
# gcloud docker -- push gcr.io/fd-slack-crypto-bot/fd-slack-crypto-bot:v1

FROM node:8

# Create app directory
WORKDIR /usr/src/app

# Bundle app source
COPY . .

# RUN apt-get update \
#     && apt-get install -qq libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++

# You have to specify "--unsafe-perm" with npm install
# when running as root.  Failing to do this can cause
# install to appear to succeed even if a preinstall
# script fails, and may have other adverse consequences
# as well.
# This command will also cat the npm-debug.log file after the
# build, if it exists.
RUN npm install --unsafe-perm || \
  ((if [ -f npm-debug.log ]; then \
      cat npm-debug.log; \
    fi) && false)

CMD [ "npm", "start" ]
